# Specify version format
version: "{build}"

# Operating system (build VM template)
os: Visual Studio 2015

# build platform, i.e. Win32 (instead of x86), x64, Any CPU. This setting is optional.
platform:
  - x64

# Do not build feature branch with open Pull Request
skip_branch_with_pr: true

skip_commits:
  files:
    .travis.yml
    .gitignore

# specify custom environment variables
environment:
  MSVC_DEFAULT_OPTIONS: ON
  OpenGR_REPOSITORY_ROOT: C:\projects\OpenGR
  OpenGR_BUILD_DIR: C:\projects\OpenGR\build
  OpenGR_RELEASE_DIR: C:\projects\OpenGR\OpenGR-%platform%-%configuration%
  OpenGR_RELEASE_NAME: OpenGR-%platform%-%configuration%

# build configuration, i.e. Debug, Release, etc.
configuration:
  - Debug
  - Release

# scripts that are called at very beginning, before repo cloning
init:
  - cmd: cmake --version
  - cmd: msbuild /version

# clone directory
clone_folder: C:\projects\OpenGR

# branches to build
branches:
  # whitelist
  # only:
  #   - master
  # blacklist
  except:
    - gh-pages

# scripts that run after cloning repository
install:

# scripts to run before build
before_build:
  - cmd: md %OpenGR_BUILD_DIR%
  - cmd: cd %OpenGR_BUILD_DIR%

  - cmd: if "%platform%"=="Win32" set CMAKE_GENERATOR_NAME=Visual Studio 14 2015
  - cmd: if "%platform%"=="x64"   set CMAKE_GENERATOR_NAME=Visual Studio 14 2015 Win64
  - cmd: cmake -G "%CMAKE_GENERATOR_NAME%" -DCMAKE_BUILD_TYPE=%configuration% -DOpenGR_COMPILE_TESTS=TRUE -DIO_USE_OPENCV=FALSE -DENABLE_TIMING=FALSE -DOpenGR_USE_CHEALPIX=FALSE -DDL_DATASETS=FALSE  -DCMAKE_INSTALL_PREFIX=%OpenGR_RELEASE_DIR% ..
  - cmd: dir .

build:
  project: C:\projects\OpenGR\build\INSTALL.vcxproj  # path to Visual Studio solution or project
  parallel: true                           # enable MSBuild parallel builds
  verbosity: quiet                         # MSBuild verbosity level (quiet|minimal|normal|detailed)

after_build:
  - cmd: cd %OpenGR_REPOSITORY_ROOT%
  - cmd: dir %OpenGR_RELEASE_DIR%

artifacts:
  - path: OpenGR-%platform%-%configuration% # use relative path
    name: OpenGR-%platform%-%configuration%
    type: zip

test: on
test_script:
  - cmd: if "%configuration%"=="Release" msbuild %OpenGR_BUILD_DIR%\buildtests.vcxproj /m /p:Configuration=%configuration%
  - cmd: if "%configuration%"=="Release" msbuild %OpenGR_BUILD_DIR%\RUN_TESTS.vcxproj  /m /p:Configuration=%configuration%
#   - cmd: ctest --build-config %configuration% --parallel 4 --output-on-failure

