# Specify version format
version: "{build}"

# Operating system (build VM template)
os: Visual Studio 2015

# build platform, i.e. Win32 (instead of x86), x64, Any CPU. This setting is optional.
platform:
  - Win32
  - x64

# Do not build feature branch with open Pull Request
skip_branch_with_pr: true

skip_commits:
  files:
    .travis.yml
    tests/*
    .gitignore

# specify custom environment variables
environment:
  MSVC_DEFAULT_OPTIONS: ON
  SUPER4PCS_INSTALL_DIR: C:\projects\Super4PCS-%platform%-%configuration%

# build configuration, i.e. Debug, Release, etc.
configuration:
  - Debug
  - Release

# scripts that are called at very beginning, before repo cloning
init:
  - cmd: cmake --version
  - cmd: msbuild /version

# clone directory
clone_folder: C:\projects\Super4PCS

# branches to build
branches:
  # whitelist
  # only:
  #   - master
  # blacklist
  except:
    - gh-pages

# scripts that run after cloning repository
install:

# scripts to run before build
before_build:
  - cmd: cd C:\projects\Super4PCS
  - cmd: md build
  - cmd: cd build

  - cmd: if "%platform%"=="Win32" set CMAKE_GENERATOR_NAME=Visual Studio 14 2015
  - cmd: if "%platform%"=="x64"   set CMAKE_GENERATOR_NAME=Visual Studio 14 2015 Win64
  - cmd: cmake -G "%CMAKE_GENERATOR_NAME%" -DCMAKE_BUILD_TYPE=%configuration% -DSUPER4PCS_COMPILE_TESTS=FALSE -DIO_USE_OPENCV=FALSE -DENABLE_TIMING=FALSE -DSUPER4PCS_USE_CHEALPIX=FALSE -DDL_DATASETS=FALSE  -DINSTALL_DIR=%SUPER4PCS_INSTALL_DIR% ..
  - cmd: dir C:\projects\Super4PCS\build

build:
  project: C:\projects\Super4PCS\build\Super4PCSINSTALL.vcxproj  # path to Visual Studio solution or project
  parallel: true                           # enable MSBuild parallel builds
  verbosity: quiet                         # MSBuild verbosity level (quiet|minimal|normal|detailed)

after_build:
  - cmd: cd %SUPER4PCS_INSTALL_DIR%
  - cmd: dir bin/
  - cmd: dir lib/

test: off
#test_script:
#  - cmd: ctest --build-config %configuration% --parallel 4 --output-on-failure

